POST http://localhost:8000/transacoes/signup 
Content-Type: application/json

{ "username": "gui", "password": "Pass1234!", "email": "gui@gmail.com" }

###

POST http://localhost:8000/transacoes/login 
Content-Type: application/json

{ "username": "gui", "password": "Pass1234!" }

###

GET http://localhost:8000/transacoes/test_token 
Content-Type: application/json
Authorization: token af7d8e4bbea9fa20ecc5fabff25e073dc8ea15b9