POST http://localhost:8000/transacoes/signup 
Content-Type: application/json

{ "username": "guii", "password": "Pass12345!", "email": "guii@gmail.com" }

###

POST http://localhost:8000/transacoes/login 
Content-Type: application/json

{ "username": "gui", "password": "Pass1234!" }

###

GET http://localhost:8000/transacoes/test_token 
Content-Type: application/json
Authorization: token 1a3743fe7bbd1b012f2b1468ffa8a68e45072d81